### ISSUE TITLE
Error when using CLI

### ISSUE THREAD

**Issue by bbockelm** [ncsa/oa4mp#148]
I'm not sure if it's a misconfiguration or a bug but, in a fairly fresh install, when using the CLI, I get the following error:

```
oa4mp>use clients
Internal error reading line:
```

This is with the debugging turned all the way up -- no obvious error message in the session.  The only command the CLI appears to accept is `quit`.

**Comment by jjg-123** [comment]
This is a Java 17 error. The issue is that the CLI uses reflection to dispatch all of its commands and that was fundamentally altered starting around Java 16.  The only solution is a substantial rewrite of the code. We have standardized on Java 11 (supported until 2032) for OA4MP and CILogon for now. Java 17 support ends in 2029, btw.

**Comment by bbockelm** [comment]
Confirmed that this is fixed by downgrading the runtime environment to Java 16 in my test container.
